sudo: required
services:
  - docker

before_install:
  - docker build -t tatilopeg/docker-react -f Dockerfile.dev .

script:
 - docker run -e CI=true tatilopeg/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "frontend-definitivo"
  env: "Frontend-definitivo-env"
  bucket_name: "elasticbeanstalk-us-east-1-194400293401"
  bucket_path: "frontend-definitivo"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"



