sudo: required
services:
  - docker

before_install:
  - docker build -t tatilopeg/docker-react -f Dockerfile.dev .

script:
 - docker run -e CI=true tatilopeg/docker-react npm run test -- --coverage

